name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Python dependencies
        run: |
          pip install flet holidays
          
      - name: Build APK
        run: |
          flet build apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # Este cambio busca cualquier archivo .apk que se haya generado
          path: build/apk/*.apk 
