name: Build Android APK
on: [push] # Se ejecuta cada vez que subes un cambio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Python dependencies
        run: |
          pip install flet holidays
      - name: Build APK
        run: |
          flet build apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/apk/app-release.apk
