name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          pip install flet holidays
          
      - name: Build APK
        run: |
          # Quitamos el --release que dio error
          flet build apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # Usamos una ruta más general para asegurar que lo encuentre
          path: "build/apk/*.apk"
